In [1]:
from sklearn.metrics import mean_squared_error

In [3]:
from sklearn.linear_model import LogisticRegression

In [4]:
best_epoch = None
best_model = None

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
from sklearn import datasets

In [8]:
iris = datasets.load_iris()

In [31]:
X, y = iris['data'][:, (2, 3)], iris['target']

In [57]:
X_train, X_test ,y_train, y_test = train_test_split(X, y,test_size = 0.2, random_state = 30)

In [58]:
import numpy as np

In [59]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
def onehot(y):
    N = y.max() + 1
    m = len(y)
    matrix = np.zeros((m, N))
    matrix[np.arange(m), y] = 1
    return matrix

In [61]:
y_test = onehot(y_test)

In [165]:
y_train = onehot(y_train)

In [63]:
def softmax(logits):
    exps = np.exp(logits)
    exp_sums = np.sum(exps, axis = 1, keepdims = True)
    return exps/exp_sums

In [96]:
X_new = np.c_[np.ones([len(X),1]), X]

In [97]:
X_train, X_test ,y_train, y_test = train_test_split(X_new, y,test_size = 0.2, random_state = 30)

In [98]:
n_inputs = X_train.shape[1]

In [100]:
n_outputs = len(np.unique(y))

In [153]:
n_inputs = X_train.shape[1] # == 3 (2 features plus the bias term)
n_outputs = len(np.unique(y_train))   # == 3 (3 iris classes)

In [154]:
Theta = np.random.randn(n_inputs, n_outputs)

In [157]:
def softmax(logits):
    exps = np.exp(logits)
    exp_sums = np.sum(exps, axis=1, keepdims=True)
    return exps / exp_sums

In [158]:
logits = X_train.dot(Theta)

In [159]:
Y_proba = softmax(logits)

In [169]:
y_train*Y_proba

array([[0.00000000e+00, 0.00000000e+00, 3.06117277e-04],
       [0.00000000e+00, 9.98733858e-01, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.63053171e-04],
       [0.00000000e+00, 0.00000000e+00, 4.52452833e-04],
       [0.00000000e+00, 0.00000000e+00, 4.02187897e-05],
       [0.00000000e+00, 0.00000000e+00, 6.16194168e-04],
       [0.00000000e+00, 9.96161234e-01, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.82186095e-04],
       [0.00000000e+00, 9.98920713e-01, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 9.04879213e-05],
       [0.00000000e+00, 0.00000000e+00, 1.83231776e-04],
       [0.00000000e+00, 0.00000000e+00, 2.26045858e-04],
       [6.78719890e-03, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 9.99367637e-01, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.78860374e-04],
       [0.00000000e+00, 9.98616570e-01, 0.00000000e+00],
       [0.00000000e+00, 9.99194923e-01, 0.00000000e+00],
       [0.00000000e+00, 9.99644

In [168]:
Y_proba.shape

(120, 3)

In [140]:
exp_sum = np.sum(exps, axis = 1,keepdims = True)

In [144]:
p = exps/exp_sum

In [152]:
p

array([[0.29064363, 0.18456057, 0.52479579],
       [0.25838439, 0.1893637 , 0.55225191],
       [0.2897294 , 0.18505562, 0.52521498],
       [0.28464782, 0.18530653, 0.53004565],
       [0.28471026, 0.18901032, 0.52627942],
       [0.30023729, 0.18088773, 0.51887498],
       [0.27117334, 0.182064  , 0.54676267],
       [0.27942354, 0.18832954, 0.53224692],
       [0.27166745, 0.18656697, 0.54176558],
       [0.2700192 , 0.19193717, 0.53804363],
       [0.29253479, 0.1849171 , 0.5225481 ],
       [0.28883769, 0.18553847, 0.52562384],
       [0.1876833 , 0.18068976, 0.63162694],
       [0.27623348, 0.18682796, 0.53693856],
       [0.28466356, 0.18624001, 0.52909643],
       [0.27753606, 0.18441773, 0.53804621],
       [0.26984142, 0.18783373, 0.54232486],
       [0.26123079, 0.19206911, 0.5467001 ],
       [0.27166745, 0.18656697, 0.54176558],
       [0.27073882, 0.18721118, 0.54205   ],
       [0.2069907 , 0.18100756, 0.61200175],
       [0.25543298, 0.19187276, 0.55269426],
       [0.

In [151]:
y_train.reshape(-1,1)*np.log(p)

array([[-2.47131479, -3.37955511, -1.28949211],
       [-1.35330693, -1.66408576, -0.59375098],
       [-2.4776158 , -3.37419769, -1.28789523],
       [-2.51300516, -3.37148785, -1.26958428],
       [-2.51256651, -3.3319073 , -1.28384598],
       [-2.40636428, -3.41975747, -1.31218462],
       [-1.30499705, -1.70339702, -0.60374045],
       [-2.55005315, -3.339124  , -1.26129552],
       [-1.30317658, -1.67896499, -0.61292188],
       [-2.61852444, -3.30117442, -1.23963123],
       [-2.45834333, -3.37569529, -1.29807648],
       [-2.48378075, -3.36898606, -1.28633891],
       [-0.        , -0.        , -0.        ],
       [-1.28650881, -1.67756709, -0.62187161],
       [-2.51289459, -3.36143811, -1.27316915],
       [-1.2818044 , -1.69055183, -0.61981083],
       [-1.30992084, -1.67219813, -0.61189009],
       [-1.342351  , -1.64990004, -0.60385489],
       [-1.30317658, -1.67896499, -0.61292188],
       [-1.30660068, -1.675518  , -0.61239704],
       [-0.        , -0.        , -0.   