# Chapter 13 Introduction to Modeling Libraries in Python

In [1]:
import numpy as np; import pandas as pd

In [2]:
data = pd.DataFrame({'x0': [1, 2, 3, 4, 5],
                     'x1': [0.01, -0.01, 0.25, -4.1, 0.],
                     'y': [-1.5, 0., 3.6, 1.3, -2.]})

In [3]:
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [4]:
data.values

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

In [5]:
df = pd.DataFrame(data.values, columns = ['one', 'two', 'three'])

In [6]:
df

one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

In [7]:
df2 = df.copy()

In [8]:
df2['strings'] = ['a', 'b', 'c', 'd', 'e']

In [9]:
df2

one   two  three strings
0  1.0  0.01   -1.5       a
1  2.0 -0.01    0.0       b
2  3.0  0.25    3.6       c
3  4.0 -4.10    1.3       d
4  5.0  0.00   -2.0       e

In [11]:
df2.values

array([[1.0, 0.01, -1.5, 'a'],
       [2.0, -0.01, 0.0, 'b'],
       [3.0, 0.25, 3.6, 'c'],
       [4.0, -4.1, 1.3, 'd'],
       [5.0, 0.0, -2.0, 'e']], dtype=object)

In [15]:
# Subset of columns
multi_cols = ['one', 'strings']

In [16]:
df2.loc[:,multi_cols]

one strings
0  1.0       a
1  2.0       b
2  3.0       c
3  4.0       d
4  5.0       e

In [17]:
data['category'] = pd.Categorical(['a', 'b', 'a', 'a', 'b'], categories = ['a', 'b'])

In [18]:
data

x0    x1    y category
0   1  0.01 -1.5        a
1   2 -0.01  0.0        b
2   3  0.25  3.6        a
3   4 -4.10  1.3        a
4   5  0.00 -2.0        b

In [19]:
dummies = pd.get_dummies(data.category)

In [20]:
dummies

a  b
0  1  0
1  0  1
2  1  0
3  1  0
4  0  1

In [25]:
data_with_dummies = data.join(dummies).drop('category', axis = 1)

In [26]:
data_with_dummies

x0    x1    y  a  b
0   1  0.01 -1.5  1  0
1   2 -0.01  0.0  0  1
2   3  0.25  3.6  1  0
3   4 -4.10  1.3  1  0
4   5  0.00 -2.0  0  1

In [27]:
data = pd.DataFrame({
....: 'x0': [1, 2, 3, 4, 5],
....: 'x1': [0.01, -0.01, 0.25, -4.1, 0.],
....: 'y': [-1.5, 0., 3.6, 1.3, -2.]})

In [28]:
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [32]:
pip install patsy

Note: you may need to restart the kernel to use updated packages.


In [33]:
import patsy

In [35]:
y,X = patsy.dmatrices('y~ x0 + x1', data) # add +0 to supress intercept

In [36]:
y

DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.0
  Terms:
    'y' (column 0)

In [37]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

In [38]:
y, X = patsy.dmatrices('y ~ x0 + np.log(np.abs(x1) + 1)', data)

In [39]:
y, X = patsy.dmatrices('y ~ standardize(x0) + center(x1)', data)

In [40]:
# use I() to specify two columns as one variable
y, X = patsy.dmatrices('y ~ I(x0 + x1)', data)

In [41]:
X

DesignMatrix with shape (5, 2)
  Intercept  I(x0 + x1)
          1        1.01
          1        1.99
          1        3.25
          1       -0.10
          1        5.00
  Terms:
    'Intercept' (column 0)
    'I(x0 + x1)' (column 1)

In [42]:
data = pd.DataFrame({
....: 'key1': ['a', 'a', 'b', 'b', 'a', 'b', 'a', 'b'],
....: 'key2': [0, 1, 0, 1, 0, 1, 0, 0],
....: 'v1': [1, 2, 3, 4, 5, 6, 7, 8],
....: 'v2': [-1, 0, 2.5, -0.5, 4.0, -1.2, 0.2, -1.7]
....: })

In [43]:
data

key1  key2  v1   v2
0    a     0   1 -1.0
1    a     1   2  0.0
2    b     0   3  2.5
3    b     1   4 -0.5
4    a     0   5  4.0
5    b     1   6 -1.2
6    a     0   7  0.2
7    b     0   8 -1.7

In [44]:
# When using non-numeric terms, like key1, they converted to dummy variables by default
y, X = patsy.dmatrices('v2 ~ key1', data)

In [45]:
X

DesignMatrix with shape (8, 2)
  Intercept  key1[T.b]
          1          0
          1          0
          1          1
          1          1
          1          0
          1          1
          1          0
          1          1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)

In [46]:
y,X = patsy.dmatrices('v2 ~ key1 + 0', data)

In [47]:
X

DesignMatrix with shape (8, 2)
  key1[a]  key1[b]
        1        0
        1        0
        0        1
        0        1
        1        0
        0        1
        1        0
        0        1
  Terms:
    'key1' (columns 0:2)

In [48]:
# Numeric columns can be interpreted as categorical with C function
y, X = patsy.dmatrices('v2 ~ C(key2)', data)

In [49]:
X

DesignMatrix with shape (8, 2)
  Intercept  C(key2)[T.1]
          1             0
          1             1
          1             0
          1             1
          1             0
          1             1
          1             0
          1             0
  Terms:
    'Intercept' (column 0)
    'C(key2)' (column 1)

In [56]:
data['key2'] = data['key2'].map({0: 'zero', 1: 'one'})

In [57]:
data

key1  key2  v1   v2  key3
0    a  zero   1 -1.0  zero
1    a   one   2  0.0   one
2    b  zero   3  2.5  zero
3    b   one   4 -0.5   one
4    a  zero   5  4.0  zero
5    b   one   6 -1.2   one
6    a  zero   7  0.2  zero
7    b  zero   8 -1.7  zero

In [58]:
y, X = patsy.dmatrices('v2 ~ key1 + key2', data)

In [59]:
X

DesignMatrix with shape (8, 3)
  Intercept  key1[T.b]  key2[T.zero]
          1          0             1
          1          0             0
          1          1             1
          1          1             0
          1          0             1
          1          1             0
          1          0             1
          1          1             1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)

In [60]:
y, X = patsy.dmatrices('v2 ~ key1 + key2 + key1:key2', data)

In [61]:
X

DesignMatrix with shape (8, 4)
  Intercept  key1[T.b]  key2[T.zero]  key1[T.b]:key2[T.zero]
          1          0             1                       0
          1          0             0                       0
          1          1             1                       1
          1          1             0                       0
          1          0             1                       0
          1          1             0                       0
          1          0             1                       0
          1          1             1                       1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)
    'key1:key2' (column 3)

## 13.3 Introduction to statsmodels

### Estimating Linear Models

In [62]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [66]:
def dnorm(mean, variance, size=1):
    if isinstance(size, int):
        size = size,
    return mean + np.sqrt(variance) * np.random.randn(*size)

In [74]:
N = 100
X = np.c_[dnorm(0, 0.4, size=N),
dnorm(0, 0.6, size=N),
dnorm(0, 0.2, size=N)]

In [75]:
eps = dnorm(0, 0.1, size=N)
beta = [0.1, 0.3, 0.5]

In [76]:
y = np.dot(X, beta) + eps

In [77]:
X_model = sm.add_constant(X)

In [87]:
model = sm.OLS(y, X)

In [88]:
result = model.fit()

In [89]:
print(result.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.525
Model:                            OLS   Adj. R-squared (uncentered):              0.510
Method:                 Least Squares   F-statistic:                              35.76
Date:                Tue, 26 May 2020   Prob (F-statistic):                    1.19e-15
Time:                        15:23:22   Log-Likelihood:                         -20.692
No. Observations:                 100   AIC:                                      47.38
Df Residuals:                      97   BIC:                                      55.20
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [91]:
data = pd.DataFrame(X, columns=['col0', 'col1', 'col2'])

In [92]:
data

col0      col1      col2
0  -0.013867  0.019414 -0.093730
1   0.833653 -0.365378  0.229535
2   0.140826 -0.686079 -0.332196
3   0.349759  0.283188  0.067399
4  -1.752584 -0.695543  0.118513
5  -0.957129 -1.624788  0.544881
6  -0.081508 -0.301877  0.045972
7   1.123248 -0.276265 -0.356387
8   0.519893 -0.958046 -0.640044
9  -1.173197 -0.099998  0.178019
10  0.195805  0.131751  0.579481
11 -1.156394  0.304205 -0.021807
12 -0.302083 -1.042239 -0.072239
13 -0.097351  0.028597 -0.012285
14  0.883951 -0.814026  0.790123
15 -0.315761 -0.047036 -0.169780
16  0.201297  1.615480  0.356310
17  1.555438 -0.332019  0.580657
18 -0.179180  0.213180 -0.195035
19 -1.026833 -1.066671 -0.372530
20 -0.423173  0.327504 -0.215450
21 -1.031460  0.854520 -0.454184
22  0.773193  0.365494 -0.370927
23  0.022052 -0.349268  0.640209
24 -0.106783  0.668401 -0.636109
25  1.469476 -1.606789  0.356151
26  0.153935  0.292185  0.201732
27 -0.138003  0.461508 -0.468920
28 -0.093202 -0.200408 -0.418561
29 -1.038583 -1.030816 -0.420805
..       ...       ...       ...
70  0.194841 -0.090871  0.153714
71 -0.443188 -0.397084 -0.101836
72  0.043049 -0.753230  0.070230
73 -0.824895  0.909638 -0.220876
74  0.073356 -1.335637 -0.740661
75 -0.692815 -0.190904 -0.151564
76  0.440685 -0.167945 -0.526250
77  0.711950 -0.426700 -0.612010
78 -0.401179 -0.420402  0.360161
79 -0.726931 -0.695941 -0.175205
80 -1.364597 -0.027541  0.104791
81 -0.185001  0.521249  0.562919
82 -0.806989  0.975023 -0.424873
83 -0.143445 -1.679463 -0.527927
84  0.792516  0.230378 -0.088157
85  0.046365 -0.205817 -0.028195
86 -0.335739  0.573394  0.231611
87  0.845782 -0.220501 -0.410536
88 -0.951526 -0.036759 -0.096208
89 -0.463109  0.012479  0.396128
90  0.021818  0.327240 -0.786689
91  0.565219  0.971319  0.570625
92 -0.403212  0.931457 -0.018227
93  1.213388  1.624943 -0.098825
94 -0.075472  0.883091  0.816452
95  0.203837  0.702903  0.498469
96  1.228175 -0.784265 -0.566712
97  0.655417 -1.295254  0.109420
98 -0.606594  0.575195  0.784013
99  0.153966 -0.764937 -0.009412

[100 rows x 3 columns]

In [94]:
data['y'] = y

In [95]:
results = smf.ols('y ~ col0 + col1 + col2', data=data).fit()

In [96]:
results.predict(data[:5])

0   -0.008523
1    0.066719
2   -0.319127
3    0.172287
4   -0.307168
dtype: float64

### Estimating Time Series Processes

In [98]:
init_x = 4
values = [init_x, init_x]

In [99]:
values[-1]

4

In [100]:
values[-2]

4

In [101]:
b0 = 0.8
b1 = -0.4
noise = dnorm(0, 0.1, N)
for i in range(N):
    new_x = values[-1] * b0 + values[-2] * b1 + noise[i]
    values.append(new_x)

In [105]:
maxlag = 5

In [106]:
model = sm.tsa.AR(values)

In [107]:
model

In [108]:
results = model.fit(maxlag)

In [112]:
results.params

array([ 0.00599531,  0.55873507, -0.37482316, -0.19067875,  0.14449476,
       -0.1700306 ])

## 13.4 Introduction to scikit-learn

In [113]:
train = pd.read_csv('train.csv')

In [114]:
test = pd.read_csv('test.csv')

In [115]:
train[:4]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [117]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [118]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [119]:
# Use Age as a predictor
train['Age'] = train['Age'].fillna(train['Age'].median())

In [120]:
test['Age'] = test['Age'].fillna(train['Age'].median())

In [121]:
train['IsFemale'] = (train['Sex'] == 'female').astype(int)

In [122]:
test['IsFemale'] = (test['Sex'] == 'female').astype(int)

In [123]:
predictors = ['Pclass', 'IsFemale', 'Age']

In [124]:
X_train = train[predictors].values

In [125]:
y_train = train['Survived'].values

In [126]:
X_train[:5]

array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.]])

In [127]:
X_test = test[predictors].values

In [128]:
from sklearn.linear_model import LogisticRegression

In [129]:
model = LogisticRegression()

In [131]:
model.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [133]:
y_predict = model.predict(X_test)

In [136]:
test[:5]

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  IsFemale  
0  34.5      0      0   330911   7.8292   NaN        Q         0  
1  47.0      1      0   363272   7.0000   NaN        S         1  
2  62.0      0      0   240276   9.6875   NaN        Q         0  
3  27.0      0      0   315154   8.6625   NaN        S         0  
4  22.0      1      1  3101298  12.2875   NaN        S         1

In [134]:
y_predict

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [135]:
y_true = test['Survived'].values

KeyError: 'Survived'

In [137]:
(y_true == y_predict).mean()

NameError: name 'y_true' is not defined