#### Numpy, short for numerical python, is one of the most important foundational packages for numerical computing

# 4.1 NumPy ndarray

In [148]:
import numpy as np

In [150]:
# Generate some random data
data = np.random.randn(2,3) # (2,3) means two rows and three columns
data

TypeError: 'tuple' object is not callable

In [142]:
data *10

array([[70.        , 70.        , 70.        , 70.        ],
       [ 0.        , 12.6786851 , 10.80570152,  0.        ],
       [70.        , 70.        , 70.        , 70.        ],
       [70.        , 70.        , 70.        , 70.        ],
       [70.        , 70.        , 70.        , 70.        ],
       [ 4.89502618,  0.        ,  0.        ,  0.        ],
       [ 0.        , 22.1130913 ,  0.        ,  7.85466237]])

In [100]:
data + data

array([[14.        , 14.        , 14.        , 14.        ],
       [ 0.        ,  2.53573702,  2.1611403 ,  0.        ],
       [14.        , 14.        , 14.        , 14.        ],
       [14.        , 14.        , 14.        , 14.        ],
       [14.        , 14.        , 14.        , 14.        ],
       [ 0.97900524,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  4.42261826,  0.        ,  1.57093247]])

In [101]:
data.shape

(7, 4)

In [102]:
data.dtype

dtype('float64')

## Creating ndarrays

In [103]:
# Use array function
data1 = [3,5,6.8,5,3]
arr1 = np.array(data1)
arr1

array([3. , 5. , 6.8, 5. , 3. ])

In [104]:
arr1.ndim

1

In [105]:
data2 = [[1,2,3,4],[5,6,7,8]] # It is a list of lists
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [106]:
arr2.ndim

2

In [107]:
arr2.shape

(2, 4)

In [108]:
arr2.dtype

dtype('int32')

In [109]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [110]:
np.empty((3,4,2))

TypeError: 'tuple' object is not callable

### arange: an array-valued version of the range function

In [111]:
np.arange(16) # from 0 to 15 (including 15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [112]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Data Types for ndarrays

In [113]:
arr1 = np.array([1,2,3], dtype = np.float64)
arr1

array([1., 2., 3.])

In [114]:
# array of strings to numbers
# use the astype() function to convert
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

## Arithmetic with NumPy Arrays

In [115]:
# +, - , *, /, **, >, <, == and so on can be applied to equal-size arrays element-wise
arr1 ** arr1

array([ 1.,  4., 27.])

## Basic Indexing and Slicing

In [116]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [117]:
# Choose one number arr[]
arr[11]

11

In [118]:
arr[4:6] # arr[start:end] from start to end-1

array([4, 5])

In [119]:
arr[4:6] = 100
arr

array([  0,   1,   2,   3, 100, 100,   6,   7,   8,   9,  10,  11])

In [120]:
arr_slice = arr[4:6] 
# This is part of arr, if you change the value here, the values in arr wiil also change
arr_slice[:] = 100000 
# [:] choose all the values
arr

array([     0,      1,      2,      3, 100000, 100000,      6,      7,
            8,      9,     10,     11])

In [121]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
arr2d[1, 2]

6

In [123]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[100,11,12]]])
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100,  11,  12]]])

In [124]:
arr3d.shape

(2, 2, 3)

In [125]:
arr3d[1]

array([[  7,   8,   9],
       [100,  11,  12]])

In [126]:
old_values = arr3d[1].copy()

In [127]:
arr3d[1] = 999
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[999, 999, 999],
        [999, 999, 999]]])

In [128]:
old_values

array([[  7,   8,   9],
       [100,  11,  12]])

## Indexing with slicess

In [129]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [132]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [133]:
arr2d[:2,2]

array([3, 6])

## Boolean Indexing

In [134]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [135]:
"""
The names =='Bob' equals to True for the first and fourth rows
It can be used to index a data metric
"""

data = np.random.randn(7,4)
data

TypeError: 'tuple' object is not callable

In [136]:
# Choose the 1st and 4th row of data
data[names == 'Bob']

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [137]:
# Choose the opposite cases: ~
data[~(names == 'Bob')]
# ~ is used to inverse a general condition

array([[0.        , 1.26786851, 1.08057015, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.48950262, 0.        , 0.        , 0.        ],
       [0.        , 2.21130913, 0.        , 0.78546624]])

In [138]:
data[data < 0] = 0
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.26786851, 1.08057015, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.48950262, 0.        , 0.        , 0.        ],
       [0.        , 2.21130913, 0.        , 0.78546624]])

In [139]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.26786851, 1.08057015, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.48950262, 0.        , 0.        , 0.        ],
       [0.        , 2.21130913, 0.        , 0.78546624]])

### Fancy Indexing

In [140]:
arr = np.empty((7, 4))
arr

TypeError: 'tuple' object is not callable